hooks:
  post-start:
    - exec: curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    - exec: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    - exec: sudo chmod 644 /usr/share/keyrings/githubcli-archive-keyring.gpg
    - exec: sudo chmod 644 /etc/apt/sources.list.d/github-cli.list
    - exec: sudo apt update
    - exec: sudo apt install gh
web_environment:
  - TERM=xterm-256color
webimage_extra_packages: [zsh]
